// Catálogo 2026: diseños propios, alojados en /public en vez de Cloudinary
export const products = [
  {
    id: 1,
    name: "Pray More Worry Less",
    price: 34.99,
    image: "/images/products/pray-more-worry-less-flat.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 2,
    name: "Chosen Loved Redeemed",
    price: 34.99,
    image: "/images/products/chosen-loved-redeemed.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 3,
    name: "Strength and Dignity",
    price: 34.99,
    image: "/images/products/strength-and-dignity.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 4,
    name: "Wildflower Warrior",
    price: 32.99,
    image: "/images/products/wildflower-warrior.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 5,
    name: "I Came I Saw I Went Home",
    price: 32.99,
    image: "/images/products/moth-i-came-i-saw.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 6,
    name: "Beach Please",
    price: 29.99,
    image: "/images/products/beach-please.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 7,
    name: "Happily Unavailable",
    price: 29.99,
    image: "/images/products/happily-unavailable.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 8,
    name: "World in His Hands",
    price: 34.99,
    image: "/images/products/world-in-his-hands.webp",
    category: "limited",
    gender: "women",
  },
  {
    id: 9,
    name: "Read Dream Bloom",
    price: 32.99,
    image: "/images/products/read-dream-bloom.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 10,
    name: "Born With Rhythm",
    price: 34.99,
    image: "/images/products/born-with-rhythm-sun.webp",
    category: "limited",
    gender: "unisex",
  },
  {
    id: 11,
    name: "Solitude is my Superpower",
    price: 32.99,
    image: "/images/products/solitude-superpower.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 12,
    name: "Alone in Space",
    price: 32.99,
    image: "/images/products/alone-in-space.webp",
    category: "limited",
    gender: "women",
  },
  {
    id: 13,
    name: "Moon Dancer",
    price: 34.99,
    image: "/images/products/moon-dancer.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 14,
    name: "Busy Do Not Disturb",
    price: 29.99,
    image: "/images/products/busy-do-not-disturb.webp",
    category: "women",
    gender: "women",
  },
  {
    id: 15,
    name: "Bold Soul",
    price: 34.99,
    image: "/images/products/bold-soul.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 16,
    name: "Dream Loud",
    price: 34.99,
    image: "/images/products/dream-loud.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 17,
    name: "Inner Force",
    price: 34.99,
    image: "/images/products/inner-force.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 18,
    name: "No Limits",
    price: 34.99,
    image: "/images/products/no-limits.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 19,
    name: "Silent Power",
    price: 34.99,
    image: "/images/products/silent-power.webp",
    category: "limited",
    gender: "unisex",
  },
  {
    id: 20,
    name: "Rhythm",
    price: 34.99,
    image: "/images/products/rhythm.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 21,
    name: "Mix Tape",
    price: 34.99,
    image: "/images/products/mix-tape-black.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 22,
    name: "Protect Your Peace",
    price: 32.99,
    image: "/images/products/protect-your-peace-1.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 23,
    name: "Gorilla Ballerina",
    price: 32.99,
    image: "/images/products/gorilla-ballerina-white.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 24,
    name: "Tokyo Land of the Rhythm",
    price: 34.99,
    image: "/images/products/tokyo-rhythm-1.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 25,
    name: "Rhythm Squad",
    price: 29.99,
    image: "/images/products/rhythm-squad-1.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 26,
    name: "I Am Watching You Dance",
    price: 32.99,
    image: "/images/products/watching-you-dance-1.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 27,
    name: "Life's Better by the Sea",
    price: 29.99,
    image: "/images/products/better-by-the-sea-1.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 28,
    name: "Cuban Flow",
    price: 34.99,
    image: "/images/products/cuban-flow.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 29,
    name: "Urban Flow",
    price: 34.99,
    image: "/images/products/urban-flow.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 30,
    name: "Legacy",
    price: 34.99,
    image: "/images/products/legacy-discipline.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 31,
    name: "Balance",
    price: 34.99,
    image: "/images/products/balance-mind-body-soul.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 32,
    name: "Street Soul",
    price: 34.99,
    image: "/images/products/street-soul.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 33,
    name: "Trust the Flow",
    price: 34.99,
    image: "/images/products/trust-the-flow.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 34,
    name: "Baila Libre",
    price: 34.99,
    image: "/images/products/baila-libre.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 35,
    name: "Created by Motion",
    price: 34.99,
    image: "/images/products/created-by-motion.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 36,
    name: "Unbound Spirit",
    price: 34.99,
    image: "/images/products/unbound-spirit.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 37,
    name: "Awaken Within",
    price: 34.99,
    image: "/images/products/awaken-within.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 38,
    name: "Unshaken Mind",
    price: 34.99,
    image: "/images/products/unshaken-mind.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 39,
    name: "Ascend Higher",
    price: 34.99,
    image: "/images/products/ascend-higher.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 40,
    name: "Reinvent Yourself",
    price: 34.99,
    image: "/images/products/reinvent-yourself.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 41,
    name: "Revolution / Evolution",
    price: 34.99,
    image: "/images/products/revolution-evolution.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 42,
    name: "Inner Revolution",
    price: 34.99,
    image: "/images/products/inner-revolution.webp",
    category: "men",
    gender: "men",
  },
  {
    id: 43,
    name: "Quiet Revolution",
    price: 34.99,
    image: "/images/products/quiet-revolution.webp",
    category: "men",
    gender: "men",
  },
]
