// Catálogo 2026: fuente única de datos de producto, usada por la grilla del shop y la ficha de detalle.
export const products = [
  {
    id: 1,
    name: "Pray More Worry Less",
    price: 34.99,
    description: "A soft, natural-tone t-shirt featuring a delicate floral wreath and the message 'Pray More, Worry Less' inspired by Philippians 4:6.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/pray-more-worry-less-flat.webp"},
    image: "/images/products/pray-more-worry-less-flat.webp",
    images: ["/images/products/pray-more-worry-less-flat.webp","/images/products/pray-more-worry-less-model.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 2,
    name: "Chosen Loved Redeemed",
    price: 34.99,
    description: "A bold statement tee reading 'Chosen. Loved. Redeemed.' inspired by 1 Peter 2:9.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/chosen-loved-redeemed.webp"},
    image: "/images/products/chosen-loved-redeemed.webp",
    images: ["/images/products/chosen-loved-redeemed.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 3,
    name: "Strength and Dignity",
    price: 34.99,
    description: "An elegant floral silhouette design with the message 'She is clothed in Strength and Dignity', inspired by Proverbs 31:25.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/strength-and-dignity.webp"},
    image: "/images/products/strength-and-dignity.webp",
    images: ["/images/products/strength-and-dignity.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 4,
    name: "Wildflower Warrior",
    price: 32.99,
    description: "A hand-drawn wildflower bouquet with the words 'Wildflower Warrior', inspired by Isaiah 41:10.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/wildflower-warrior.webp"},
    image: "/images/products/wildflower-warrior.webp",
    images: ["/images/products/wildflower-warrior.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 5,
    name: "I Came I Saw I Went Home",
    price: 32.99,
    description: "A celestial moth design paired with the introvert-approved line 'I came. I saw. I went home.'",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/moth-i-came-i-saw.webp"},
    image: "/images/products/moth-i-came-i-saw.webp",
    images: ["/images/products/moth-i-came-i-saw.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 6,
    name: "Beach Please",
    price: 29.99,
    description: "A playful beach-themed tee with flip flops, seashells and the pun 'Beach Please'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/beach-please.webp"},
    image: "/images/products/beach-please.webp",
    images: ["/images/products/beach-please.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 7,
    name: "Happily Unavailable",
    price: 29.99,
    description: "A meditating frog on a lily pad with the funny caption 'Happily Unavailable — est. since forever'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Sage"],
    colorImages: {"Sage":"/images/products/happily-unavailable.webp"},
    image: "/images/products/happily-unavailable.webp",
    images: ["/images/products/happily-unavailable.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 8,
    name: "World in His Hands",
    price: 34.99,
    description: "A minimalist line-art globe held by two hands, with the message 'He's got the whole world in His hands.'",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/world-in-his-hands.webp"},
    image: "/images/products/world-in-his-hands.webp",
    images: ["/images/products/world-in-his-hands.webp"],
    category: "limited",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 9,
    name: "Read Dream Bloom",
    price: 32.99,
    description: "A stack of books surrounded by florals with the words 'Read, Dream, Bloom' — made for book lovers.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/read-dream-bloom.webp"},
    image: "/images/products/read-dream-bloom.webp",
    images: ["/images/products/read-dream-bloom.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 10,
    name: "Born With Rhythm",
    price: 34.99,
    description: "A radiant sun design surrounded by maracas and music notes with the phrase 'Born With Rhythm — est. in the groove'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/born-with-rhythm-sun.webp"},
    image: "/images/products/born-with-rhythm-sun.webp",
    images: ["/images/products/born-with-rhythm-sun.webp"],
    category: "limited",
    gender: "unisex",
    rating: 0,
    reviews: 0,
  },
  {
    id: 11,
    name: "Solitude is my Superpower",
    price: 32.99,
    description: "A cozy mushroom cottage illustration with the message 'Solitude is my Superpower'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/solitude-superpower.webp"},
    image: "/images/products/solitude-superpower.webp",
    images: ["/images/products/solitude-superpower.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 12,
    name: "Alone in Space",
    price: 32.99,
    description: "A cute cartoon astronaut floating among planets and stars with the caption 'Alone in Space, Exactly as Planned'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Sage"],
    colorImages: {"Sage":"/images/products/alone-in-space.webp"},
    image: "/images/products/alone-in-space.webp",
    images: ["/images/products/alone-in-space.webp"],
    category: "limited",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 13,
    name: "Moon Dancer",
    price: 34.99,
    description: "A dancer silhouette on a crescent moon surrounded by percussion instruments, with the phrase 'Born With Rhythm — children of the beat'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/moon-dancer.webp"},
    image: "/images/products/moon-dancer.webp",
    images: ["/images/products/moon-dancer.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 14,
    name: "Busy Do Not Disturb",
    price: 29.99,
    description: "A sleepy black cat curled up on an open book under a crescent moon, with the caption 'Busy: Do Not Disturb'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/busy-do-not-disturb.webp"},
    image: "/images/products/busy-do-not-disturb.webp",
    images: ["/images/products/busy-do-not-disturb.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 15,
    name: "Bold Soul",
    price: 34.99,
    description: "An oversized tee with the statement 'Bold Soul — urban spirit / inner strength'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Sand"],
    colorImages: {"Sand":"/images/products/bold-soul.webp"},
    image: "/images/products/bold-soul.webp",
    images: ["/images/products/bold-soul.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 16,
    name: "Dream Loud",
    price: 34.99,
    description: "An oversized tee with the statement 'Dream Loud — chase / create / inspire'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Sand"],
    colorImages: {"Sand":"/images/products/dream-loud.webp"},
    image: "/images/products/dream-loud.webp",
    images: ["/images/products/dream-loud.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 17,
    name: "Inner Force",
    price: 34.99,
    description: "An oversized black tee with the statement 'Inner Force — strong mind / strong life'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/inner-force.webp"},
    image: "/images/products/inner-force.webp",
    images: ["/images/products/inner-force.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 18,
    name: "No Limits",
    price: 34.99,
    description: "An oversized tee with the statement 'No Limits — mind over everything'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/no-limits.webp"},
    image: "/images/products/no-limits.webp",
    images: ["/images/products/no-limits.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 19,
    name: "Silent Power",
    price: 34.99,
    description: "An oversized black tee with the statement 'Silent Power — discipline built within'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/silent-power.webp"},
    image: "/images/products/silent-power.webp",
    images: ["/images/products/silent-power.webp"],
    category: "limited",
    gender: "unisex",
    rating: 0,
    reviews: 0,
  },
  {
    id: 20,
    name: "Rhythm",
    price: 34.99,
    description: "An oversized tee with the vertical typographic statement 'Rhythm — feel it, don't force it'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/rhythm.webp"},
    image: "/images/products/rhythm.webp",
    images: ["/images/products/rhythm.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 21,
    name: "Mix Tape",
    price: 34.99,
    description: "A vintage-wash tee featuring a bold cassette-tape character with sunglasses, headphones and gold chain — 'Mix Tape'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Black","White"],
    colorImages: {"Black":"/images/products/mix-tape-black.webp","White":"/images/products/mix-tape-white.webp"},
    image: "/images/products/mix-tape-black.webp",
    images: ["/images/products/mix-tape-black.webp","/images/products/mix-tape-white.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 22,
    name: "Protect Your Peace",
    price: 32.99,
    description: "An ornate sea turtle mandala design with the message 'Protect Your Peace — Deep Waters, Still Soul'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/protect-your-peace-1.webp"},
    image: "/images/products/protect-your-peace-1.webp",
    images: ["/images/products/protect-your-peace-1.webp","/images/products/protect-your-peace-2.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 23,
    name: "Gorilla Ballerina",
    price: 32.99,
    description: "A muscular gorilla dancing en pointe in a tutu — a playful, unexpected illustration for the confident and unbothered.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White","Black"],
    colorImages: {"White":"/images/products/gorilla-ballerina-white.webp","Black":"/images/products/gorilla-ballerina-black.webp"},
    image: "/images/products/gorilla-ballerina-white.webp",
    images: ["/images/products/gorilla-ballerina-white.webp","/images/products/gorilla-ballerina-black.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 24,
    name: "Tokyo Land of the Rhythm",
    price: 34.99,
    description: "A streetwear-inspired gorilla in sunglasses and cap, with Tokyo skyline and the statement 'Tokyo — Land of the Rhythm'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/tokyo-rhythm-1.webp"},
    image: "/images/products/tokyo-rhythm-1.webp",
    images: ["/images/products/tokyo-rhythm-1.webp","/images/products/tokyo-rhythm-2.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 25,
    name: "Rhythm Squad",
    price: 29.99,
    description: "A fun retro grid of eight monkey icons in sunglasses and headphones, for music lovers who don't take themselves too seriously.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/rhythm-squad-1.webp"},
    image: "/images/products/rhythm-squad-1.webp",
    images: ["/images/products/rhythm-squad-1.webp","/images/products/rhythm-squad-2.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 26,
    name: "I Am Watching You Dance",
    price: 32.99,
    description: "A striking watercolor eye design paired with the bold statement 'I Am Watching You Dance'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/watching-you-dance-1.webp"},
    image: "/images/products/watching-you-dance-1.webp",
    images: ["/images/products/watching-you-dance-1.webp","/images/products/watching-you-dance-2.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 27,
    name: "Life's Better by the Sea",
    price: 29.99,
    description: "A retro beach-icon grid — palm tree, wave, sunset and hibiscus — with the message 'Life's Better by the Sea'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/better-by-the-sea-1.webp"},
    image: "/images/products/better-by-the-sea-1.webp",
    images: ["/images/products/better-by-the-sea-1.webp","/images/products/better-by-the-sea-2.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 28,
    name: "Cuban Flow",
    price: 34.99,
    description: "An oversized white tee with the statement 'Cuban Flow — sabor / ritmo / calle'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["White"],
    colorImages: {"White":"/images/products/cuban-flow.webp"},
    image: "/images/products/cuban-flow.webp",
    images: ["/images/products/cuban-flow.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 29,
    name: "Urban Flow",
    price: 34.99,
    description: "An oversized olive tee with the statement 'Urban Flow — move with purpose'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Olive"],
    colorImages: {"Olive":"/images/products/urban-flow.webp"},
    image: "/images/products/urban-flow.webp",
    images: ["/images/products/urban-flow.webp","/images/products/urban-flow-2.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 30,
    name: "Legacy",
    price: 34.99,
    description: "An oversized sage tee with the statement 'Legacy — made by discipline'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Sage"],
    colorImages: {"Sage":"/images/products/legacy-discipline.webp"},
    image: "/images/products/legacy-discipline.webp",
    images: ["/images/products/legacy-discipline.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 31,
    name: "Balance",
    price: 34.99,
    description: "An oversized cream tee with the vertical statement 'Balance — mind / body / soul'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/balance-mind-body-soul.webp"},
    image: "/images/products/balance-mind-body-soul.webp",
    images: ["/images/products/balance-mind-body-soul.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 32,
    name: "Street Soul",
    price: 34.99,
    description: "An oversized black tee with the vertical statement 'Street Soul — urban culture / inner fire'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/street-soul.webp"},
    image: "/images/products/street-soul.webp",
    images: ["/images/products/street-soul.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 33,
    name: "Trust the Flow",
    price: 34.99,
    description: "An oversized olive tee with the vertical statement 'Trust the Flow — move with purpose'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Olive"],
    colorImages: {"Olive":"/images/products/trust-the-flow.webp"},
    image: "/images/products/trust-the-flow.webp",
    images: ["/images/products/trust-the-flow.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 34,
    name: "Baila Libre",
    price: 34.99,
    description: "An oversized cream tee with the vertical statement 'Baila Libre — sabor / calle / corazón'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/baila-libre.webp"},
    image: "/images/products/baila-libre.webp",
    images: ["/images/products/baila-libre.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 35,
    name: "Created by Motion",
    price: 34.99,
    description: "An oversized black tee with the vertical statement 'Created by Motion — driven by purpose'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/created-by-motion.webp"},
    image: "/images/products/created-by-motion.webp",
    images: ["/images/products/created-by-motion.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 36,
    name: "Unbound Spirit",
    price: 34.99,
    description: "An oversized white tee with the statement 'Unbound Spirit — beyond limits / beyond fear'.",
    sizes: ["One Size"],
    colors: ["White"],
    colorImages: {"White":"/images/products/unbound-spirit.webp"},
    image: "/images/products/unbound-spirit.webp",
    images: ["/images/products/unbound-spirit.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 37,
    name: "Awaken Within",
    price: 34.99,
    description: "An oversized black tee with the statement 'Awaken Within — wake the fire within'.",
    sizes: ["One Size"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/awaken-within.webp"},
    image: "/images/products/awaken-within.webp",
    images: ["/images/products/awaken-within.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 38,
    name: "Unshaken Mind",
    price: 34.99,
    description: "An oversized beige tee with the statement 'Unshaken Mind — pressure cannot break you'.",
    sizes: ["One Size"],
    colors: ["Sand"],
    colorImages: {"Sand":"/images/products/unshaken-mind.webp"},
    image: "/images/products/unshaken-mind.webp",
    images: ["/images/products/unshaken-mind.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 39,
    name: "Ascend Higher",
    price: 34.99,
    description: "An oversized white tee with the statement 'Ascend Higher — rise beyond the ordinary'.",
    sizes: ["One Size"],
    colors: ["White"],
    colorImages: {"White":"/images/products/ascend-higher.webp"},
    image: "/images/products/ascend-higher.webp",
    images: ["/images/products/ascend-higher.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 40,
    name: "Reinvent Yourself",
    price: 34.99,
    description: "An oversized black tee with the statement 'Reinvent Yourself — destroy the old / create the new'.",
    sizes: ["One Size"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/reinvent-yourself.webp"},
    image: "/images/products/reinvent-yourself.webp",
    images: ["/images/products/reinvent-yourself.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 41,
    name: "Revolution / Evolution",
    price: 34.99,
    description: "An oversized black tee with the statement 'Revolution / Evolution — become what comes next'.",
    sizes: ["One Size"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/revolution-evolution.webp"},
    image: "/images/products/revolution-evolution.webp",
    images: ["/images/products/revolution-evolution.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 42,
    name: "Inner Revolution",
    price: 34.99,
    description: "An oversized off-white tee with the vertical statement 'Inner Revolution — break the pattern / create your path'.",
    sizes: ["One Size"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/inner-revolution.webp"},
    image: "/images/products/inner-revolution.webp",
    images: ["/images/products/inner-revolution.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 43,
    name: "Quiet Revolution",
    price: 34.99,
    description: "An oversized olive tee with the statement 'Quiet Revolution — no noise / just movement'.",
    sizes: ["One Size"],
    colors: ["Olive"],
    colorImages: {"Olive":"/images/products/quiet-revolution.webp"},
    image: "/images/products/quiet-revolution.webp",
    images: ["/images/products/quiet-revolution.webp"],
    category: "men",
    gender: "men",
    rating: 0,
    reviews: 0,
  },
  {
    id: 44,
    name: "Bloom Within",
    price: 34.99,
    description: "An oversized natural tee with the statement 'Bloom Within — soft growth / quiet strength'.",
    sizes: ["One Size"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/bloom-within.webp"},
    image: "/images/products/bloom-within.webp",
    images: ["/images/products/bloom-within.webp","/images/products/bloom-within-model.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 45,
    name: "Pure Form",
    price: 34.99,
    description: "An oversized black tee with the statement 'Pure Form — shape / soul / silence'.",
    sizes: ["One Size"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/pure-form.webp"},
    image: "/images/products/pure-form.webp",
    images: ["/images/products/pure-form.webp","/images/products/pure-form-model.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 46,
    name: "She Dances",
    price: 34.99,
    description: "An oversized white tee with the statement 'She Dances — rhythm / grace / soul'.",
    sizes: ["One Size"],
    colors: ["White"],
    colorImages: {"White":"/images/products/she-dances.webp"},
    image: "/images/products/she-dances.webp",
    images: ["/images/products/she-dances.webp","/images/products/she-dances-model.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 47,
    name: "Soul Bloom",
    price: 34.99,
    description: "An oversized natural tee with the statement 'Soul Bloom — soft growth / inner calm'.",
    sizes: ["One Size"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/soul-bloom.webp"},
    image: "/images/products/soul-bloom.webp",
    images: ["/images/products/soul-bloom.webp","/images/products/soul-bloom-model.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 48,
    name: "Wild Grace",
    price: 34.99,
    description: "An oversized black tee with the statement 'Wild Grace — calm / bold / free'.",
    sizes: ["One Size"],
    colors: ["Black"],
    colorImages: {"Black":"/images/products/wild-grace.webp"},
    image: "/images/products/wild-grace.webp",
    images: ["/images/products/wild-grace.webp","/images/products/wild-grace-model.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 49,
    name: "She Moves",
    price: 34.99,
    description: "An oversized sage tee with the statement 'She Moves — grace in motion'.",
    sizes: ["One Size"],
    colors: ["Sage"],
    colorImages: {"Sage":"/images/products/she-moves.webp"},
    image: "/images/products/she-moves.webp",
    images: ["/images/products/she-moves.webp","/images/products/she-moves-model.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 50,
    name: "Wild Nectar",
    price: 34.99,
    description: "A fitted natural tee with the statement 'Wild Nectar — light / freedom / bloom'.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Natural"],
    colorImages: {"Natural":"/images/products/wild-nectar.webp"},
    image: "/images/products/wild-nectar.webp",
    images: ["/images/products/wild-nectar.webp","/images/products/wild-nectar-model.webp"],
    category: "women",
    gender: "women",
    rating: 0,
    reviews: 0,
  },
  {
    id: 51,
    name: "Soft Rebellion",
    price: 36.99,
    description: "An oversized pink tee with the statement 'Soft Rebellion — gentle is not fragile'.",
    sizes: ["One Size"],
    colors: ["Pink"],
    colorImages: {"Pink":"/images/products/soft-rebellion.webp"},
    image: "/images/products/soft-rebellion.webp",
    images: ["/images/products/soft-rebellion.webp"],
    category: "limited",
    gender: "unisex",
    rating: 0,
    reviews: 0,
  },
  {
    id: 52,
    name: "Midnight Theory",
    price: 36.99,
    description: "An oversized navy tee with the vertical statement 'Midnight Theory — ideas live after dark'.",
    sizes: ["One Size"],
    colors: ["Navy"],
    colorImages: {"Navy":"/images/products/midnight-theory.webp"},
    image: "/images/products/midnight-theory.webp",
    images: ["/images/products/midnight-theory.webp"],
    category: "limited",
    gender: "unisex",
    rating: 0,
    reviews: 0,
  },
  {
    id: 53,
    name: "Unwritten",
    price: 36.99,
    description: "An oversized white tee with the statement 'Unwritten — the future has no template'.",
    sizes: ["One Size"],
    colors: ["White"],
    colorImages: {"White":"/images/products/unwritten.webp"},
    image: "/images/products/unwritten.webp",
    images: ["/images/products/unwritten.webp"],
    category: "limited",
    gender: "unisex",
    rating: 0,
    reviews: 0,
  },
]

// Mapeo de nombres de colores a valores CSS. Varios nombres usados en el
// catálogo (Sand, Sage, Natural, Charcoal...) no son colores CSS válidos,
// por eso hace falta este mapeo en vez de usar el nombre directamente.
export const colorMap: Record<string, string> = {
  Black: "#000000",
  White: "#ffffff",
  Gray: "#808080",
  Navy: "#000080",
  Pink: "#FFC0CB",
  Green: "#008000",
  Cream: "#FFFDD0",
  Charcoal: "#36454F",
  Natural: "#F1EDE4",
  Sage: "#B2C2AE",
  Sand: "#D9CBB8",
  Olive: "#5C5A42",
}

// Si el producto tiene una sola talla y un solo color, esa es la variante
// que se puede agregar directamente al carrito sin pasar por la ficha.
// Si hay más de una opción, no se debe adivinar: hay que llevar al cliente
// a la ficha para que elija.
export function getQuickAddVariant(product) {
  if (product.sizes.length === 1 && product.colors.length === 1) {
    return { size: product.sizes[0], color: product.colors[0] }
  }
  return null
}
